version: 2
updates:
  - package-ecosystem: npm
    directory: /itability-fe
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/board-service
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/member-service
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/report-service
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/gateway-server
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/config-server
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    directory: /itability-be/eureka-server
    schedule:
      interval: monthly
