server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    database: ${SPRING_JPA_DATABASE}
    properties:
      hibernate:
        '[format_sql]': ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: ${SPRING_JPA_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS}
  mvc:
    view:
      suffix: ${SPRING_MVC_VIEW_SUFFIX}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

webdriver:
  chrome:
    driver: ${WEBDRIVER_CHROME_DRIVER}

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID}
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
