kakao:
  client-id: 07ce58e2be371237617b428cfa96da83
  redirect-uri: http://localhost:8080/login/kakao

naver:
  client-id: a2KVUc9JeKQMFoEelxoy
  client-secret: u2adQPCsBp
  redirect-uri: http://localhost:8080/login/naver

google:
  client-id: 529642165041-sv8fd7c0sb7to66f25t1h98av3qhmomv.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/login/google


