services:
  mariadb:
    image: mariadb:10.11
    container_name: itability-mariadb
    ports:
      - "${DB_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - mariadb-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: itability-elasticsearch
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  mariadb-data:
  es-data:
